config/routes.rb
Rails.application.routes.draw do
  resources :plantes do
	  resources :remedes
	  resources :poisons
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plante.rb
class Plante < ApplicationRecord
	validates_uniqueness_of :nomScientifique
	validates_presence_of :nomCommun, :nomScientifique
	has_many :remedes
	has_many :poisons
end

app/models/poison.rb
class Poison < ApplicationRecord
  belongs_to :plante
end

app/models/remede.rb
class Remede < ApplicationRecord
  belongs_to :plante
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plantes_controller.rb
class PlantesController < ApplicationController
  before_action :set_plante, only: [:show, :edit, :update, :destroy]

  # GET /plantes
  # GET /plantes.json
  def index
	  @plantes = Plante.all.order(:nomCommun)
  end

  # GET /plantes/1
  # GET /plantes/1.json
  def show
	  fresh_when(@gplante)
  end

  # GET /plantes/new
  def new
    @plante = Plante.new
  end

  # GET /plantes/1/edit
  def edit
  end

  # POST /plantes
  # POST /plantes.json
  def create
    @plante = Plante.new(plante_params)

    respond_to do |format|
      if @plante.save
        format.html { redirect_to @plante, notice: 'Plante was successfully created.' }
        format.json { render :show, status: :created, location: @plante }
      else
        format.html { render :new }
        format.json { render json: @plante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plantes/1
  # PATCH/PUT /plantes/1.json
  def update
    respond_to do |format|
      if @plante.update(plante_params)
        format.html { redirect_to @plante, notice: 'Plante was successfully updated.' }
        format.json { render :show, status: :ok, location: @plante }
      else
        format.html { render :edit }
        format.json { render json: @plante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plantes/1
  # DELETE /plantes/1.json
  def destroy
    @plante.destroy
    respond_to do |format|
      format.html { redirect_to plantes_url, notice: 'Plante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plante
      @plante = Plante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plante_params
      params.require(:plante).permit(:nomCommun, :nomScientifique, :description, :dimension, :fleur, :tige, :feuille, :racine, :fruit)
    end
end

app/controllers/poisons_controller.rb
class PoisonsController < ApplicationController
  before_action :set_poison, only: [:show, :edit, :update, :destroy]
  before_action :get_plante

  def get_plante
	  @plante =  Plante.find(params[:plante_id])
  end

  # GET /poisons
  # GET /poisons.json
  def index
	  @poisons = @plante.poisons.all
  end

  # GET /poisons/1
  # GET /poisons/1.json
  def show
	  @poison = @plante.poisons.find(params[:id])
	  fresh_when(@poison)
  end

  # GET /poisons/new
  def new
    @poison = Poison.new
  end

  # GET /poisons/1/edit
  def edit
  end

  # POST /poisons
  # POST /poisons.json
  def create
    @poison = Poison.new(poison_params)

    respond_to do |format|
      if @poison.save
        format.html { redirect_to plante_poisons_path, notice: 'Poison was successfully created.' }
        format.json { render :show, status: :created, location: @poison }
      else
        format.html { render :new }
        format.json { render json: @poison.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poisons/1
  # PATCH/PUT /poisons/1.json
  def update
    respond_to do |format|
      if @poison.update(poison_params)
        format.html { redirect_to plante_poisons_path, notice: 'Poison was successfully updated.' }
        format.json { render :show, status: :ok, location: @poison }
      else
        format.html { render :edit }
        format.json { render json: @poison.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poisons/1
  # DELETE /poisons/1.json
  def destroy
    @poison.destroy
    respond_to do |format|
      format.html { redirect_to plante_poisons_path, notice: 'Poison was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poison
      @poison = Poison.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poison_params
      params.require(:poison).permit(:action, :medium, :toxicite, :partiePlante, :infoComplementaire, :plante_id)
    end
end

app/controllers/remedes_controller.rb
class RemedesController < ApplicationController
  before_action :set_remede, only: [:show, :edit, :update, :destroy]
  before_action :get_plante

  def get_plante
	  @plante = Plante.find(params[:plante_id])
  end

  # GET /remedes
  # GET /remedes.json
  def index
	  @remedes = @plante.remedes.all
  end

  # GET /remedes/1
  # GET /remedes/1.json
  def show
	  @remede = @plante.remedes.find(params[:id])
	  fresh_when(@remede)
  end

  # GET /remedes/new
  def new
    @remede = Remede.new
  end

  # GET /remedes/1/edit
  def edit
  end

  # POST /remedes
  # POST /remedes.json
  def create
    @remede = Remede.new(remede_params)

    respond_to do |format|
      if @remede.save
        format.html { redirect_to plante_remedes_path, notice: 'Remede was successfully created.' }
        format.json { render :show, status: :created, location: @remede }
      else
        format.html { render :new }
        format.json { render json: @remede.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /remedes/1
  # PATCH/PUT /remedes/1.json
  def update
    respond_to do |format|
      if @remede.update(remede_params)
        format.html { redirect_to plante_remedes_path, notice: 'Remede was successfully updated.' }
        format.json { render :show, status: :ok, location: @remede }
      else
        format.html { render :edit }
        format.json { render json: @remede.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remedes/1
  # DELETE /remedes/1.json
  def destroy
    @remede.destroy
    respond_to do |format|
      format.html { redirect_to plante_remedes_path, notice: 'Remede was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remede
      @remede = Remede.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def remede_params
      params.require(:remede).permit(:modeAdministration, :partiePlante, :maux, :infoComplementaire, :plante_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plantes_helper.rb
module PlantesHelper
end

app/helpers/poisons_helper.rb
module PoisonsHelper
end

app/helpers/remedes_helper.rb
module RemedesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Herboriste</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plantes/_form.html.erb
<%= form_with(model: plante, local: true) do |form| %>
  <% if plante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plante.errors.count, "error") %> prohibited this plante from being saved:</h2>

      <ul>
      <% plante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nomCommun %>
    <%= form.text_field :nomCommun, id: :plante_nomCommun %>
  </div>

  <div class="field">
    <%= form.label :nomScientifique %>
    <%= form.text_field :nomScientifique, id: :plante_nomScientifique %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :plante_description %>
  </div>

  <div class="field">
    <%= form.label :dimension %>
    <%= form.text_field :dimension, id: :plante_dimension %>
  </div>

  <div class="field">
    <%= form.label :fleur %>
    <%= form.text_field :fleur, id: :plante_fleur %>
  </div>

  <div class="field">
    <%= form.label :tige %>
    <%= form.text_field :tige, id: :plante_tige %>
  </div>

  <div class="field">
    <%= form.label :feuille %>
    <%= form.text_field :feuille, id: :plante_feuille %>
  </div>

  <div class="field">
    <%= form.label :racine %>
    <%= form.text_field :racine, id: :plante_racine %>
  </div>

  <div class="field">
    <%= form.label :fruit %>
    <%= form.text_field :fruit, id: :plante_fruit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plantes/edit.html.erb
<h1>Editing Plante</h1>

<%= render 'form', plante: @plante %>

<%= link_to 'Show', @plante %> |
<%= link_to 'Back', plantes_path %>

app/views/plantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plantes</h1>

<table>
  <thead>
    <tr>
      <th>Nom commun</th>
      <th>Nom scientifique</th>
      <th>Description</th>
      <th>Localisationn</th>
      <th>Description de la fleur</th>
      <th>Description de la tige</th>
      <th>Description de la feuille</th>
      <th>Description de la racine</th>
      <th>Description du fruit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plantes.each do |plante| %>
      <tr>
        <td><%= plante.nomCommun %></td>
        <td><%= plante.nomScientifique %></td>
        <td><%= plante.description %></td>
        <td><%= plante.dimension %></td>
        <td><%= plante.fleur %></td>
        <td><%= plante.tige %></td>
        <td><%= plante.feuille %></td>
        <td><%= plante.racine %></td>
        <td><%= plante.fruit %></td>
        <td><%= link_to 'Show', plante %></td>
        <td><%= link_to 'Edit', edit_plante_path(plante) %></td>
        <td><%= link_to 'Destroy', plante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plante', new_plante_path %>

app/views/plantes/new.html.erb
<h1>New Plante</h1>

<%= render 'form', plante: @plante %>

<%= link_to 'Back', plantes_path %>

app/views/plantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nomcommun:</strong>
  <%= @plante.nomCommun %>
</p>

<p>
  <strong>Nomscientifique:</strong>
  <%= @plante.nomScientifique %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plante.description %>
</p>

<p>
  <strong>Dimension:</strong>
  <%= @plante.dimension %>
</p>

<p>
  <strong>Fleur:</strong>
  <%= @plante.fleur %>
</p>

<p>
  <strong>Tige:</strong>
  <%= @plante.tige %>
</p>

<p>
  <strong>Feuille:</strong>
  <%= @plante.feuille %>
</p>

<p>
  <strong>Racine:</strong>
  <%= @plante.racine %>
</p>

<p>
  <strong>Fruit:</strong>
  <%= @plante.fruit %>
</p>

<%= link_to 'Remedes', plante_remedes_path(@plante) %>
<%= link_to 'Poisons', plante_poisons_path(@plante) %>
<%= link_to 'Edit', edit_plante_path(@plante) %> |
<%= link_to 'Back', plantes_path %>

app/views/poisons/_form.html.erb
<%= form_for([@plante, @poison]) do |form| %>
  <% if poison.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poison.errors.count, "error") %> prohibited this poison from being saved:</h2>

      <ul>
      <% poison.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :action %>
    <%= form.text_field :action, id: :poison_action %>
  </div>

  <div class="field">
    <%= form.label :medium %>
    <%= form.text_field :medium, id: :poison_medium %>
  </div>

  <div class="field">
    <%= form.label :toxicite %>
    <%= form.text_field :toxicite, id: :poison_toxicite %>
  </div>

  <div class="field">
    <%= form.label :partiePlante %>
    <%= form.text_field :partiePlante, id: :poison_partiePlante %>
  </div>

  <div class="field">
    <%= form.label :infoComplementaire %>
    <%= form.text_area :infoComplementaire, id: :poison_infoComplementaire %>
  </div>

  <div class="field">
    <%= form.label :plante_id %>
    <%= collection_select(:poison, :plante_id, Plante.all, :id, :nomCommun) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/poisons/edit.html.erb
<h1>Editing Poison</h1>

<%= render 'form', poison: @poison %>

<%= link_to 'Show', plante_poison_path(@plante, @poison) %> |
<%= link_to 'Back', plante_poisons_path %>

app/views/poisons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poisons</h1>

<table>
  <thead>
    <tr>
      <th>Action</th>
      <th>Medium</th>
      <th>Toxicite</th>
      <th>Partieplante</th>
      <th>Infocomplementaire</th>
      <th>Plante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poisons.each do |poison| %>
      <tr>
        <td><%= poison.action %></td>
        <td><%= poison.medium %></td>
        <td><%= poison.toxicite %></td>
        <td><%= poison.partiePlante %></td>
        <td><%= poison.infoComplementaire %></td>
        <td><%= poison.plante.nomScientifique %></td>
        <td><%= link_to 'Show', plante_poison_path(@plante, poison) %></td>
        <td><%= link_to 'Edit', edit_plante_poison_path(@plante, poison) %></td>
        <td><%= link_to 'Destroy', [@plante, poison], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poison', new_plante_poison_path %>

app/views/poisons/new.html.erb
<h1>New Poison</h1>

<%= render 'form', poison: @poison %>

<%= link_to 'Back', plante_poisons_path %>

app/views/poisons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plante:</strong>
  <%= @poison.plante.nomScientifique%>
</p>

<p>
  <strong>Action:</strong>
  <%= @poison.action %>
</p>

<p>
  <strong>Medium:</strong>
  <%= @poison.medium %>
</p>

<p>
  <strong>Toxicite:</strong>
  <%= @poison.toxicite %>
</p>

<p>
  <strong>Partieplante:</strong>
  <%= @poison.partiePlante %>
</p>

<p>
  <strong>Infocomplementaire:</strong>
  <%= @poison.infoComplementaire %>
</p>

<%= link_to 'Edit', edit_plante_poison_path(@poison) %> |
<%= link_to 'Back', plante_poisons_path %>

app/views/remedes/_form.html.erb
<%= form_for([@plante, @remede]) do |form| %>
  <% if remede.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(remede.errors.count, "error") %> prohibited this remede from being saved:</h2>

      <ul>
      <% remede.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :modeAdministration %>
    <%= form.text_field :modeAdministration, id: :remede_modeAdministration %>
  </div>

  <div class="field">
    <%= form.label :partiePlante %>
    <%= form.text_field :partiePlante, id: :remede_partiePlante %>
  </div>

  <div class="field">
    <%= form.label :maux %>
    <%= form.text_field :maux, id: :remede_maux %>
  </div>

  <div class="field">
    <%= form.label :infoComplementaire %>
    <%= form.text_area :infoComplementaire, id: :remede_infoComplementaire %>
  </div>

  <div class="field">
    <%= form.label :plante_id %>
    <%= collection_select(:remede, :plante_id, Plante.all, :id, :nomCommun) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/remedes/edit.html.erb
<h1>Editing Remede</h1>

<%= render 'form', remede: @remede %>

<%= link_to 'Show', plante_remede_path(@plante, @remede) %> |
<%= link_to 'Back', plante_remedes_path(@plante) %>

app/views/remedes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Remedes</h1>

<table>
  <thead>
    <tr>
      <th>Modeadministration</th>
      <th>Partieplante</th>
      <th>Maux</th>
      <th>Infocomplementaire</th>
      <th>Plante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @remedes.each do |remede| %>
      <tr>
        <td><%= remede.modeAdministration %></td>
        <td><%= remede.partiePlante %></td>
        <td><%= remede.maux %></td>
        <td><%= remede.infoComplementaire %></td>
        <td><%= remede.plante.nomScientifique %></td>
        <td><%= link_to 'Show', plante_remede_path(@plante, remede) %></td>
	<td><%= link_to 'Edit', edit_plante_remede_path(@plante, remede) %></td>
	<td><%= link_to 'Destroy', [@plante, remede], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Remede', new_plante_remede_path(@plante) %>

app/views/remedes/new.html.erb
<h1>New Remede</h1>

<%= render 'form', remede: @remede %>

<%= link_to 'Back', plante_remedes_path(@plante) %>

app/views/remedes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<h1>
		<strong>Plante:</strong>
		<%= @remede.plante.nomScientifique %>
	</h1>
</p>

<p>
  <strong>Modeadministration:</strong>
  <%= @remede.modeAdministration %>
</p>

<p>
  <strong>Partieplante:</strong>
  <%= @remede.partiePlante %>
</p>

<p>
  <strong>Maux:</strong>
  <%= @remede.maux %>
</p>

<p>
  <strong>Infocomplementaire:</strong>
  <%= @remede.infoComplementaire %>
</p>


<%= link_to 'Edit', edit_plante_remede_path(@remede) %> |